config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # get 'lists/index'
  # get 'lists/show'
  # get 'lists/new'
  # get 'movies/index'
  # get 'movies/show'
  # get 'movies/new'
  # get 'movies/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #get "lists/movieshow", to: "lists#movieshow", as: "lists_movieshow"
  root to: "lists#index"
  delete "lists/:id", to: "lists#destroy", as: :list_delete
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end

  #resources :lists, only: :destroy, as: :list
  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id, message: "should be unique for a given movie/list couple" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: { message: "is a required field" }
  validates :name, uniqueness: { message: "must be unique" }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: { message: "is a required field" }
  validates :title, uniqueness: { message: "must be unique" }
  validates :overview, presence: { message: "is a required field" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  #before_action :set_bookmark, only: [:show]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end


   private

  # def set_bookmark
  #   @bookmark = Bookmark.find(params[:id])
  # end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def movieshow
  #   @movies = Movie.all
  # end

  def destroy
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a Movie & Comment to your <%= @list.name %> List</h3>
        <br>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :movie_id, collection: @movies, include_blank: 'Select a Movie', input_html: {data: { controller: "tom-select"}}  %>
          <%= f.input :comment, placeholder: 'Enter a comment about this movie', input_html: { class: 'textarea'}  %>
          <%= f.button :submit, 'Add Movie', class:"button"%>
           <%= button_tag 'Cancel', type: 'button', class: 'button-back text-decoration-none', onclick: "window.location.href='#{list_path(@list)}'" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render"shared/navbar" %>
      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner-img container-fluid d-flex justify-content-center align-items-center">
  <div>
    <h1>Your Own Movie Lists!</h1>
  </div>
</div>

<div class = "container-fluid  pb-3">
  <div class="cotainerr d-flex justify-content-between align-items-center pt-3">
    <h2>My Lists</h2>
    <%= link_to "Create a List", new_list_path, class: "button text-decoration-none"%>
  </div>

  <div class="grid">
    <%# <% image_filenames = ['micky-background.jpg', 'elsa-background.jpg', 'winnie-background.jpg'] %>
    <%# <% shuffled_images = image_filenames.shuffle %>
    <% @lists.each_with_index do |list, i| %>
      <div class="card">
        <%= link_to list_path(list), class:"text-decoration-none" do %>
          <div class="card-img" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path('imgcard.jpg') %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/movieshow.html.erb
<h1>movies Present</h1>

<ol>
<%@movies.each do |movie|%>
  <li><%=movie.title%></li>
<%end%>
</ol>

app/views/lists/new.html.erb
<div class = "container-fluid py-5 pb-3">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-4 mt-5 shadow">
        <h2>Add a New List</h2>
        <br>
        <%= simple_form_for(@list) do |f| %>
          <%= f.input :name, placeholder: 'Fantasy' %>
          <%= f.submit class:"button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mt-4 pb-5">
  <h1><%=@list.name%></h1>
  <br>
  <%@list.movies.each do |movie|%>
    <div class="mt-5 d-flex movie-card-show">
      <div>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <h2><strong><%= movie.title %></strong></h2>
        <h3 class="mb-4 mt-4"><%= movie.overview %></h3>
        <%= link_to bookmark_path(bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the movie from this list?" } do %>
          <i class="fas fa-trash"></i> Delete
        <% end %>
      </div>
      <div class="d-flex flex-column ms-5">
        <h3 class="mb-4 mt-4"><strong>Rating: </strong><%= movie.rating %></h3>
        <%= image_tag(movie.poster_url, style: "max-width: 600px; max-height: 600px;") %>
      </div>
    </div>
    <br>
  <%end%>
  <br>
  <br>
  <%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "button text-decoration-none"%>
  <%= link_to "Back to Lists", root_path, class: "button text-decoration-none"%>
  <%# <% list_to_delete = List.find(params[:id])%>
  <%= link_to "Delete This List", list_delete_path(@list), class: "button text-decoration-none", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "movie-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "btn btn-primary text-decoration-none nav-link m-1" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "btn btn-primary text-decoration-none nav-link m-1" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>